; MineVision Guardian — ESP32-S3-WROOM-N16R8 (octal PSRAM)
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.psram_type = opi
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -I include
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  adafruit/Adafruit BME280 Library@^2.2.4
  mikalhart/TinyGPSPlus@^1.0.3
  olikraus/U8g2@^2.35.30
